CREATE USER porta WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'porta';
CREATE DATABASE "tasks" OWNER=porta;
CREATE DATABASE "cloudscan" OWNER=porta;
CREATE DATABASE "payment" OWNER=porta;
CREATE DATABASE "company-profile" OWNER=porta;
CREATE DATABASE "workflow" OWNER=porta;
CREATE DATABASE "product-engine-buyer" OWNER=porta;
CREATE DATABASE "eventstore" OWNER=porta;
CREATE DATABASE "product-engine-objectstore" OWNER=porta;
CREATE DATABASE "product-engine-business-audit" OWNER=porta;
CREATE DATABASE "collaboration" OWNER=porta;
CREATE DATABASE "supplier-management" OWNER=porta;
CREATE DATABASE "exchange_rates" OWNER=porta;
CREATE DATABASE "product-tax-service" OWNER=porta;
CREATE DATABASE "apps" OWNER=porta;
CREATE DATABASE "product-engine-supplier" OWNER=porta;
CREATE DATABASE "portaudit" OWNER=porta;
CREATE DATABASE "proforma" OWNER=porta;